spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5436/marathon
    password: trackme
  jpa:
    hibernate:
      ddl-auto: create-drop

api:
  server:
    url: http://localhost:8080